### ISSUE TITLE
Unauthorized to create EFS storage class

### ISSUE THREAD

**Issue by ChristianBergen** [dspace-group/simphera-reference-architecture-aws#138]
When creating infrastructure with GPU nodepool, creation of the EFS storage class fails with "Unauthorized".

![image](https://github.com/dspace-group/simphera-reference-architecture-aws/assets/87411832/c7d7c90e-b086-4037-a334-f4d039fa74ff)

Currently there is no solution for this error, but a workaround exists. The storage class has to be created manually with the already created EFS file system id.

**Comment by fmense** [comment]
Just as a remark: Today I used g5.4xlarge nodes instead of p3.2xlarge and the error did not occur. 
The problem might be related to the kind of GPU nodes.

**Comment by tmisch** [comment]
The reason for this is the expiration time of `15m` for the default token that is created/queried on EKS cluster creation.
If some operation takes too long, e.g. the initial _scale up_ of a GPU node instance to avoid _scale from 0_ problems, the token expires before the EFS storage classes is created.

This can be solved in the definition of the `kubernetes` provider by **not** specifying `token = data.aws_eks_cluster_auth.cluster.token` argument. Instead, the following configuration causes a new token to be get automatically:

```
exec {
  api_version = "client.authentication.k8s.io/v1beta1"
  args = ["eks", "get-token", "--profile", "change_me", "--cluster-name", data.aws_eks_cluster.cluster.name]
  command = "aws"
}
```

See <https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#exec-plugins> for details.
